name: Release Builds

on:
  workflow_dispatch:
  push:
    branches:
      - main

jobs:
  build-all:
    name: Build All Platforms
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      - name: Set up Go
        uses: actions/setup-go@v4
        with:
          go-version: '1.21'

      - name: Generate timestamp
        id: timestamp
        run: echo "timestamp=$(date +'%Y%m%d%H%M')" >> $GITHUB_OUTPUT

      - name: Build All
        run: |
          # Linux AMD64
          GOOS=linux GOARCH=amd64 CGO_ENABLED=0 go build -ldflags="-s -w" -o mini_dlna_updater_linux_amd64
          
          # Linux ARM64
          GOOS=linux GOARCH=arm64 CGO_ENABLED=0 go build -ldflags="-s -w" -o mini_dlna_updater_linux_arm64
          
          # Windows AMD64
          GOOS=windows GOARCH=amd64 CGO_ENABLED=0 go build -ldflags="-s -w" -o mini_dlna_updater_windows_amd64.exe

      - name: Create Release
        uses: softprops/action-gh-release@v1
        with:
          tag_name: build-${{ steps.timestamp.outputs.timestamp }}
          name: Automated Build ${{ steps.timestamp.outputs.timestamp }}
          files: |
            mini_dlna_updater_*
          prerelease: true
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
